"""Graph kit file apply: lock, drift check, adopt, revert, regions, headers."""

from __future__ import annotations

import hashlib
import json
from dataclasses import replace
from pathlib import Path

import pytest

from code_review_graph.contract import COMPAT_EPOCH
from code_review_graph.harness.apply import KIT_VERSION, LOCK_NAME, STATE_DIR, apply, render_kit
from code_review_graph.harness.targets import KIT_DIR, Region, Target, get_target

HEADER = f"GENERATED by crg-kit {KIT_VERSION} — do not edit"
CLAUDE_MD = "# rules\n<!-- crg-kit:begin graph-routing -->\n<!-- crg-kit:end graph-routing -->\n"


def _claude_root(root: Path) -> Path:
    """A claude root as shipped: CLAUDE.md carries the graph-routing markers."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "CLAUDE.md").write_text(CLAUDE_MD, encoding="utf-8")
    return root


def _snapshot(root: Path) -> dict[str, bytes]:
    return {
        p.relative_to(root).as_posix(): p.read_bytes()
        for p in sorted(root.rglob("*"))
        if p.is_file() and STATE_DIR not in p.relative_to(root).parts
    }


def _backups(root: Path) -> list[Path]:
    base = root / STATE_DIR / "backup"
    return sorted(base.iterdir()) if base.is_dir() else []


def _kind(report, kind: str) -> list[str]:
    return [path for k, path in report.drift if k == kind]


def test_apply_twice_is_idempotent(tmp_path: Path):
    _claude_root(tmp_path)
    first = apply("claude", tmp_path)
    assert first.status == 0 and first.written
    snap = _snapshot(tmp_path)
    second = apply("claude", tmp_path)
    assert second.status == 0
    assert second.written == [] and second.drift == [] and second.backup is None
    assert _snapshot(tmp_path) == snap
    assert len(_backups(tmp_path)) == 1


def test_lock_records_every_file(tmp_path: Path):
    apply("claude", tmp_path)
    lock = json.loads((tmp_path / LOCK_NAME).read_text(encoding="utf-8"))
    assert lock["kit_version"] == KIT_VERSION
    assert lock["compat_epoch"] == COMPAT_EPOCH
    assert lock["target"] == "claude"
    assert set(lock["files"]) == set(render_kit(get_target("claude"))) >= {
        "hooks/crg-update.py", "hooks/crg_rules.json", "skills/graph-bootstrap/SKILL.md",
    }
    for rel, digest in lock["files"].items():
        assert hashlib.sha256((tmp_path / rel).read_bytes()).hexdigest() == digest


def test_headers_follow_file_syntax(tmp_path: Path):
    apply("zcode", tmp_path)
    skill = (tmp_path / "skills/graph-bootstrap/SKILL.md").read_text(encoding="utf-8")
    assert skill.startswith("---\nname: graph-bootstrap\n")
    assert f"---\n<!-- {HEADER} -->\n" in skill
    assert "Rules live in `AGENTS.md`" in skill and "ApplyPatch" in skill
    hook = (tmp_path / "hooks/crg-update.py").read_text(encoding="utf-8")
    assert hook.startswith(f"#!/usr/bin/env python3\n# {HEADER}\n")
    assert (tmp_path / "hooks/crg-update.py").stat().st_mode & 0o111
    rules = (tmp_path / "hooks/crg_rules.json").read_text(encoding="utf-8")
    assert "GENERATED" not in rules and json.loads(rules)["version"] == 1


def test_target_conditionals_differ(tmp_path: Path):
    apply("claude", tmp_path / "c")
    skill = (tmp_path / "c/skills/graph-bootstrap/SKILL.md").read_text(encoding="utf-8")
    assert "ApplyPatch" not in skill and "`CLAUDE.md`" in skill


def test_check_reports_missing_and_modified(tmp_path: Path):
    _claude_root(tmp_path)
    assert apply("claude", tmp_path, check=True).status == 1
    apply("claude", tmp_path)
    assert apply("claude", tmp_path, check=True).status == 0

    (tmp_path / "hooks/crg_rules.json").unlink()
    (tmp_path / "skills/graph-bootstrap/SKILL.md").write_text("edited\n", encoding="utf-8")
    before = _snapshot(tmp_path)
    report = apply("claude", tmp_path, check=True)
    assert report.status == 1
    assert _kind(report, "missing") == ["hooks/crg_rules.json"]
    assert _kind(report, "modified") == ["skills/graph-bootstrap/SKILL.md"]
    assert _snapshot(tmp_path) == before


def test_modified_file_is_refused_then_adopted_then_reverted(tmp_path: Path):
    _claude_root(tmp_path)
    apply("claude", tmp_path)
    skill = tmp_path / "skills/graph-bootstrap/SKILL.md"
    skill.write_text("my edit\n", encoding="utf-8")
    (tmp_path / "hooks/crg_rules.json").unlink()

    refused = apply("claude", tmp_path)
    assert refused.status == 1 and refused.refused == ["skills/graph-bootstrap/SKILL.md"]
    assert skill.read_text(encoding="utf-8") == "my edit\n"
    assert not (tmp_path / "hooks/crg_rules.json").exists()  # nothing written at all

    adopted = apply("claude", tmp_path, adopt=True)
    assert adopted.status == 0
    assert HEADER in skill.read_text(encoding="utf-8")
    assert apply("claude", tmp_path, check=True).status == 0
    saved = adopted.backup / "files/skills/graph-bootstrap/SKILL.md"
    assert saved.read_text(encoding="utf-8") == "my edit\n"

    reverted = apply("claude", tmp_path, revert=True)
    assert reverted.status == 0
    assert skill.read_text(encoding="utf-8") == "my edit\n"
    assert not (tmp_path / "hooks/crg_rules.json").exists()
    assert apply("claude", tmp_path, check=True).status == 1


def test_unowned_existing_file_needs_adopt(tmp_path: Path):
    _claude_root(tmp_path)
    hook = tmp_path / "hooks/crg-update.py"
    hook.parent.mkdir(parents=True)
    hook.write_text("#!/bin/sh\necho mine\n", encoding="utf-8")
    report = apply("claude", tmp_path)
    assert report.status == 1 and _kind(report, "unowned") == ["hooks/crg-update.py"]
    assert hook.read_text(encoding="utf-8") == "#!/bin/sh\necho mine\n"
    assert not (tmp_path / LOCK_NAME).exists()
    assert apply("claude", tmp_path, adopt=True).status == 0


def test_revert_of_first_apply_removes_everything(tmp_path: Path):
    (tmp_path / "keep.txt").write_text("user\n", encoding="utf-8")
    apply("claude", tmp_path)
    assert apply("claude", tmp_path, revert=True).status == 0
    assert _snapshot(tmp_path) == {"keep.txt": b"user\n"}
    assert apply("claude", tmp_path, revert=True).status == 1  # nothing left to revert


def _kit(tmp_path: Path, files: dict[str, str]) -> Path:
    kit = tmp_path / "kit"
    for rel, text in files.items():
        path = kit / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return kit


def test_file_dropped_from_kit_is_removed_unless_edited(tmp_path: Path):
    root = tmp_path / "root"
    kit = _kit(tmp_path, {"data/a.json": "{}\n", "data/b.json": "[]\n"})
    # The fake kit has no blocks, so this file-lifecycle test drops the claude region.
    target = replace(get_target("claude"), regions=())
    apply(target, root, kit_dir=kit)
    (kit / "data/b.json").unlink()
    check = apply(target, root, kit_dir=kit, check=True)
    assert _kind(check, "unexpected") == ["hooks/b.json"]
    report = apply(target, root, kit_dir=kit)
    assert report.removed == ["hooks/b.json"] and not (root / "hooks/b.json").exists()

    (kit / "data/a.json").unlink()
    (root / "hooks/a.json").write_text('{"edited": true}\n', encoding="utf-8")
    refused = apply(target, root, kit_dir=kit)
    assert refused.status == 1 and (root / "hooks/a.json").exists()


def _region_target(file: str = "AGENTS.md") -> Target:
    return Target(
        name="laya", regions_only=True, vars={"rules_file": "AGENTS.md"},
        regions=(Region(file=file, id="graph-search", block="graph-search"),),
    )


def test_region_is_filled_and_surrounding_bytes_kept(tmp_path: Path):
    before = "# Laya\n\nhand text\n<!-- crg-kit:begin graph-search -->\n"
    after = "<!-- crg-kit:end graph-search -->\nmore hand text\n"
    agents = tmp_path / "AGENTS.md"
    agents.write_text(before + after, encoding="utf-8")

    report = apply(_region_target(), tmp_path)
    assert report.status == 0 and report.written == ["AGENTS.md"]
    text = agents.read_text(encoding="utf-8")
    assert text.startswith(before) and text.endswith(after)
    body = text[len(before):-len(after)]
    assert body.startswith(f"<!-- {HEADER} -->\n") and "code-review-graph" in body
    assert apply(_region_target(), tmp_path, check=True).status == 0
    assert apply(_region_target(), tmp_path).written == []

    agents.write_text(text.replace("Grep is", "grep IS"), encoding="utf-8")
    refused = apply(_region_target(), tmp_path)
    assert refused.status == 1 and refused.refused == ["AGENTS.md#graph-search"]


def test_region_missing_is_reported_without_editing(tmp_path: Path):
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# no markers\n", encoding="utf-8")
    report = apply(_region_target(), tmp_path)
    assert report.status == 3
    assert _kind(report, "region-missing") == ["AGENTS.md#graph-search"]
    assert agents.read_text(encoding="utf-8") == "# no markers\n"
    assert apply(_region_target(), tmp_path, check=True).status == 1


def test_dry_run_writes_nothing(tmp_path: Path):
    _claude_root(tmp_path)
    report = apply("claude", tmp_path, dry_run=True)
    assert report.status == 0
    assert len(_kind(report, "missing")) == len(render_kit(get_target("claude")))
    assert _kind(report, "outdated") == ["CLAUDE.md#graph-routing"]
    assert list(tmp_path.iterdir()) == [tmp_path / "CLAUDE.md"]
    assert (tmp_path / "CLAUDE.md").read_text(encoding="utf-8") == CLAUDE_MD


@pytest.mark.parametrize("target", ["claude", "bug-hunter"])
def test_bare_root_is_degraded_on_missing_claude_md_region(tmp_path: Path, target: str):
    report = apply(target, tmp_path)
    assert report.status == 3
    assert _kind(report, "region-missing") == ["CLAUDE.md#graph-routing"]
    assert "hooks/crg-update.py" in report.written and not (tmp_path / "CLAUDE.md").exists()
    assert apply(target, tmp_path, check=True).status == 1


@pytest.mark.parametrize(
    ("target", "prefix"),
    [
        ("claude", "mcp__code-review-graph__"),
        ("bug-hunter", "mcp__plugin_bug-hunter_code-review-graph__"),
    ],
)
def test_graph_routing_region_is_filled_in_claude_md(tmp_path: Path, target: str, prefix: str):
    _claude_root(tmp_path)
    report = apply(target, tmp_path)
    assert report.status == 0 and "CLAUDE.md" in report.written
    text = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert text.startswith("# rules\n<!-- crg-kit:begin graph-routing -->\n")
    assert text.endswith("<!-- crg-kit:end graph-routing -->\n")
    assert f"<!-- {HEADER} -->" in text and f"`{prefix}<tool>`" in text
    assert apply(target, tmp_path, check=True).status == 0


def test_targets_without_default_root_need_one():
    with pytest.raises(ValueError, match="--root"):
        apply("bug-hunter")


def test_packaged_kit_has_every_section():
    for section in ("hooks", "skills", "blocks", "data"):
        assert any((KIT_DIR / section).iterdir()), section
