"""Graph kit directive engine: parity with zcode's render-agents, and marker regions."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from code_review_graph.harness.renderer import (
    RegionMissingError,
    RenderError,
    build_roles,
    read_region,
    render_text,
    replace_region,
)


def _zcode_harness() -> Path | None:
    candidates = [
        os.environ.get("ZCODE_HARNESS_DIR"),
        "/home/user/zcode-harness",
        str(Path.home() / "zcode-harness"),
        str(Path.home() / ".zcode" / "harness"),
    ]
    for candidate in candidates:
        if candidate and (Path(candidate) / "bin" / "render-agents").is_file():
            return Path(candidate)
    return None


ZCODE = _zcode_harness()
needs_zcode = pytest.mark.skipif(ZCODE is None, reason="zcode-harness checkout not available")


def _render_with_zcode(src: Path, out: Path) -> dict[str, str]:
    assert ZCODE is not None
    out.mkdir()
    result = subprocess.run(
        [sys.executable, str(ZCODE / "bin" / "render-agents"), "--src", str(src),
         "--zcode-dir", str(out)],
        capture_output=True, text=True, timeout=60,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return {p.name: p.read_text(encoding="utf-8") for p in sorted(out.glob("*.md"))}


def _render_with_kit(src: Path, out: Path) -> dict[str, str]:
    out.mkdir()
    for (harness, name), text in build_roles(src).items():
        assert harness == "zcode"
        (out / name).write_text(text, encoding="utf-8")
    return {p.name: p.read_text(encoding="utf-8") for p in sorted(out.glob("*.md"))}


@needs_zcode
def test_parity_with_render_agents_on_real_agent_src(tmp_path: Path):
    assert ZCODE is not None
    src = ZCODE / "agent-src"
    theirs = _render_with_zcode(src, tmp_path / "zcode")
    ours = _render_with_kit(src, tmp_path / "kit")
    # render-agents also copies passthrough files; those are not rendered roles.
    cfg = json.loads((src / "harnesses.json").read_text(encoding="utf-8"))
    for name in cfg["zcode"].get("passthrough", []):
        theirs.pop(name, None)
    assert len(theirs) >= 2
    assert ours.keys() == theirs.keys()
    for name in theirs:
        assert ours[name] == theirs[name], name


@needs_zcode
def test_parity_with_render_agents_on_every_directive(tmp_path: Path):
    src = tmp_path / "src"
    (src / "roles").mkdir(parents=True)
    (src / "blocks").mkdir()
    (src / "blocks" / "outer.md").write_text("outer {{greeting}}\n{{block:inner}}\n")
    (src / "blocks" / "inner.md").write_text("inner <!-- if:zcode -->Z<!-- endif -->\n")
    (src / "harnesses.json").write_text(json.dumps({"zcode": {
        "targets": [], "effort_key": "thoughtLevel",
        "models": {"work": "inherit", "deep": "M"}, "effort_map": {"high": "high"},
        "skills_prefix": "/skills/", "vars": {"greeting": "hi"},
        "model_line": "Model {model} {effort}.", "model_line_inherit": "Inherit {effort}.",
    }}))
    (src / "roles" / "alpha.md").write_text(
        "---\nname: alpha\ndescription: Alpha {{who}}\ntier: work\neffort: high\n"
        "skills: a, b\nharnesses: zcode\nwho.zcode: zed\n---\n\n"
        "# alpha\n\n{{model_line}}\n<!-- if:zcode -->\nzcode only\n<!-- endif -->\n"
        "<!-- if:claude -->\nclaude only\n<!-- endif -->\n"
        "{{block:outer}}\nmissing {{nothing|fallback}} and {{who}}\n"
    )
    (src / "roles" / "beta.md").write_text(
        "---\nname: beta\ndescription: Beta\ntier: deep\neffort: high\nharnesses: zcode\n---\n\n"
        "inline <!-- if:claude -->C<!-- endif --><!-- if:zcode -->Z<!-- endif --> end\n"
    )
    theirs = _render_with_zcode(src, tmp_path / "zcode")
    ours = _render_with_kit(src, tmp_path / "kit")
    assert ours == theirs
    assert "zcode only" in ours["alpha.md"] and "claude only" not in ours["alpha.md"]
    assert "missing fallback and zed" in ours["alpha.md"]


@needs_zcode
def test_parity_with_render_agents_on_kit_markers_and_home(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    src = tmp_path / "src"
    (src / "roles").mkdir(parents=True)
    (src / "blocks").mkdir()
    (src / "blocks" / "routing.md").write_text(
        "<!-- GENERATED by crg-kit 1.2.3 — do not edit -->\n"
        "<!-- crg-kit:begin graph-routing -->\nroute {{rules_file}}\n"
        "  <!-- crg-kit:end graph-routing -->\n"
    )
    (src / "harnesses.json").write_text(json.dumps({"zcode": {
        "targets": [], "effort_key": "thoughtLevel",
        "models": {"work": "inherit"}, "effort_map": {"high": "high"},
        "skills_prefix": "~/skills/", "vars": {"rules_file": "~/AGENTS.md"},
        "model_line": "Model {model} {effort}.", "model_line_inherit": "Inherit {effort}.",
    }}))
    (src / "roles" / "alpha.md").write_text(
        "---\nname: alpha\ndescription: Alpha\ntier: work\neffort: high\n"
        "skills: a\nharnesses: zcode\n---\n\n# alpha\n{{block:routing}}\nend\n"
    )
    ours = _render_with_kit(src, tmp_path / "kit")
    home = str(tmp_path / "home")
    assert f"route {home}/AGENTS.md\nend\n" in ours["alpha.md"]
    assert f"skills: {home}/skills/a\n" in ours["alpha.md"]
    # render-agents strips crg-kit marker lines and the GENERATED header from
    # roles exactly like the kit does, so kit-marked roles render identically
    # on both sides (strip-parity).
    theirs = _render_with_zcode(src, tmp_path / "zcode")
    assert ours == theirs

    # Stripping covers crg-kit markers only: a directive neither engine
    # recognizes (no endif here) is still a hard error for render-agents.
    broken = tmp_path / "broken"
    (broken / "roles").mkdir(parents=True)
    (broken / "blocks").mkdir()
    (broken / "harnesses.json").write_text((src / "harnesses.json").read_text(encoding="utf-8"))
    (broken / "roles" / "alpha.md").write_text(
        "---\nname: alpha\ndescription: Alpha\ntier: work\neffort: high\n"
        "harnesses: zcode\n---\n\n# alpha\n<!-- if:zcode -->\nunterminated\n"
    )
    with pytest.raises(AssertionError, match="leftover directive"):
        _render_with_zcode(broken, tmp_path / "zcode-broken")


def test_kit_file_rendering_keeps_region_markers():
    text = (
        "<!-- GENERATED by crg-kit 1.2.3 — do not edit -->\n"
        "<!-- crg-kit:begin r -->\nbody\n<!-- crg-kit:end r -->\n"
    )
    assert render_text(text, "claude", _lookup({}), {}) == text


def _lookup(values: dict[str, str]):
    return values.get


def test_target_alternation_and_hyphenated_targets():
    text = (
        "<!-- if:claude|bug-hunter -->\nboth\n<!-- endif -->\n"
        "a <!-- if:zcode -->Z<!-- endif -->b\n"
    )
    assert render_text(text, "bug-hunter", _lookup({}), {}) == "both\na b\n"
    assert render_text(text, "zcode", _lookup({}), {}) == "a Zb\n"


def test_nested_includes_and_defaults():
    blocks = {"a": "A {{x|dx}}\n{{block:b}}\n", "b": "B {{y}}\n"}
    out = render_text("{{block:a}}\n", "claude", _lookup({"y": "why"}), blocks)
    assert out == "A dx\nB why\n"


@pytest.mark.parametrize(
    ("text", "blocks"),
    [("{{block:nope}}\n", {}), ("{{unset}}\n", {}), ("<!-- if:zcode -->\nopen\n", {})],
)
def test_render_errors(text: str, blocks: dict[str, str]):
    with pytest.raises(RenderError):
        render_text(text, "zcode", _lookup({}), blocks)


def test_region_replace_keeps_every_surrounding_byte():
    before = "# Title\r\n\nhand text  \n<!-- crg-kit:begin graph -->\n"
    after = "<!-- crg-kit:end graph -->\ntrailing\n\n"
    text = before + "old line 1\nold line 2\n" + after
    out = replace_region(text, "graph", "new body")
    assert out == before + "new body\n" + after
    assert read_region(out, "graph") == "new body\n"
    assert replace_region(out, "graph", "new body\n") == out


def test_region_hash_comment_form_and_other_ids_untouched():
    text = (
        "x = 1\n# crg-kit:begin one\nold\n# crg-kit:end one\n"
        "<!-- crg-kit:begin two -->\nkeep\n<!-- crg-kit:end two -->\n"
    )
    out = replace_region(text, "one", "new\n")
    assert out == text.replace("old\n", "new\n")


def test_missing_region_is_reported_not_edited():
    with pytest.raises(RegionMissingError):
        replace_region("no markers here\n", "graph", "x")
    with pytest.raises(RegionMissingError):
        read_region("<!-- crg-kit:begin graph -->\nno end\n", "graph")
