"""Write the graph kit's own files into a harness root. Files only, never JSON config.

Ownership is recorded in ``<root>/.crg-kit.lock.json`` as the sha256 of every
file (and marker region) the kit wrote. A file whose bytes still match the
lock is ours to update or remove; anything else is drift:

- ``missing``: the kit ships it and it is not on disk;
- ``outdated``: ours and unedited, but the kit changed (apply fixes it);
- ``modified``: ours, but edited since (apply refuses unless ``adopt``);
- ``unowned``: a file the kit ships already exists and was never ours
  (apply refuses unless ``adopt``);
- ``unexpected``: ours, but the kit no longer ships it (apply removes it);
- ``region-missing``: a hand-maintained file lacks the kit's markers
  (reported, never edited).

``adopt`` lets the kit take such files over; the old bytes go to the backup
first. Every apply that changes something first copies what it replaces to
``<root>/.crg-kit/backup/<timestamp>/``; ``revert`` restores the newest one (``revert_backup``).
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .. import __version__
from ..locking import EXIT_DEGRADED, EXIT_ERROR, EXIT_OK
from .renderer import RegionMissingError, load_blocks, read_region, render_text, replace_region
from .targets import KIT_DIR, Target, get_target

KIT_VERSION = __version__
LOCK_NAME = ".crg-kit.lock.json"
STATE_DIR = ".crg-kit"
_KIT_SECTIONS = ("hooks", "skills", "data")

_HTML_COMMENT = {".md", ".markdown", ".html", ".htm", ".xml"}
_HASH_COMMENT = {".py", ".sh", ".bash", ".toml", ".yaml", ".yml", ".txt", ".cfg", ".ini"}
_SLASH_COMMENT = {".js", ".mjs", ".cjs", ".ts"}


def _compat_epoch() -> int:
    from ..contract import COMPAT_EPOCH

    return COMPAT_EPOCH


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def header_line(rel: str, version: str = KIT_VERSION) -> str | None:
    """The GENERATED comment for ``rel``'s file type; None where there is no comment syntax."""
    text = f"GENERATED by crg-kit {version} — do not edit"
    suffix = Path(rel).suffix.lower()
    if suffix in _HTML_COMMENT:
        return f"<!-- {text} -->"
    if suffix in _HASH_COMMENT:
        return f"# {text}"
    if suffix in _SLASH_COMMENT:
        return f"// {text}"
    return None


def add_header(rel: str, text: str, version: str = KIT_VERSION) -> str:
    """Insert the header after a shebang or YAML frontmatter, else at the top."""
    line = header_line(rel, version)
    if line is None:
        return text
    if text.startswith("#!"):
        first, _, rest = text.partition("\n")
        return f"{first}\n{line}\n{rest}"
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            cut = end + len("\n---\n")
            return f"{text[:cut]}{line}\n{text[cut:]}"
    return f"{line}\n{text}"


def render_kit(target: Target, kit_dir: Path = KIT_DIR) -> dict[str, str]:
    """Root-relative posix path -> final file text for every kit-owned file."""
    if target.regions_only:
        return {}
    blocks = load_blocks(kit_dir / "blocks")
    dest = {"hooks": target.hooks_dir, "skills": target.skills_dir, "data": target.data_dir}
    out: dict[str, str] = {}
    for section in _KIT_SECTIONS:
        base = kit_dir / section
        if not base.is_dir():
            continue
        for src in sorted(p for p in base.rglob("*") if p.is_file()):
            if "__pycache__" in src.parts:
                continue
            rel = (Path(dest[section]) / src.relative_to(base)).as_posix()
            text = render_text(
                src.read_text(encoding="utf-8"), target.name, target.vars.get, blocks, rel,
            )
            out[rel] = add_header(rel, text)
    return out


def render_regions(target: Target, kit_dir: Path = KIT_DIR) -> dict[tuple[str, str], str]:
    """(file, region id) -> region body the kit owns."""
    blocks = load_blocks(kit_dir / "blocks")
    out: dict[tuple[str, str], str] = {}
    for region in target.regions:
        if region.block not in blocks:
            raise ValueError(f"region {region.id!r}: unknown kit block {region.block!r}")
        body = render_text(
            blocks[region.block], target.name, target.vars.get, blocks, region.block,
        )
        if not body.endswith("\n"):
            body += "\n"
        line = header_line(region.file)
        out[(region.file, region.id)] = f"{line}\n{body}" if line else body
    return out


@dataclass
class ApplyReport:
    target: str
    root: Path
    mode: str
    drift: list[tuple[str, str]] = field(default_factory=list)
    written: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    refused: list[str] = field(default_factory=list)
    backup: Path | None = None
    status: int = EXIT_OK
    message: str = ""

    def lines(self) -> list[str]:
        out = [f"{kind.upper():15} {path}" for kind, path in self.drift]
        out += [f"WROTE           {p}" for p in self.written]
        out += [f"REMOVED         {p}" for p in self.removed]
        if self.refused:
            out.append(
                "refused: modified or unowned files; rerun with --adopt to take them over "
                "(the current bytes are backed up first): " + ", ".join(self.refused)
            )
        if self.backup is not None:
            out.append(f"backup: {self.backup}")
        if self.message:
            out.append(self.message)
        return out


@dataclass
class _Plan:
    lock: dict[str, Any]
    writes: dict[str, bytes] = field(default_factory=dict)
    removes: list[str] = field(default_factory=list)
    region_writes: dict[str, bytes] = field(default_factory=dict)
    new_lock: dict[str, Any] = field(default_factory=dict)


def read_lock(root: Path) -> dict[str, Any]:
    path = root / LOCK_NAME
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: not a JSON object")
    return data


def _lock_text(lock: dict[str, Any]) -> bytes:
    return (json.dumps(lock, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _plan(
    target: Target, root: Path, kit_dir: Path, report: ApplyReport, adopt: bool,
) -> _Plan:
    lock = read_lock(root)
    owned: dict[str, str] = dict(lock.get("files", {}))
    owned_regions: dict[str, str] = dict(lock.get("regions", {}))
    plan = _Plan(lock=lock)
    files: dict[str, str] = {}
    regions: dict[str, str] = {}

    for rel, text in render_kit(target, kit_dir).items():
        data = text.encode("utf-8")
        want = _sha(data)
        files[rel] = want
        path = root / rel
        if not path.is_file():
            report.drift.append(("missing", rel))
            plan.writes[rel] = data
            continue
        have = _sha(path.read_bytes())
        if have == want:
            continue
        if owned.get(rel) == have:
            report.drift.append(("outdated", rel))
        else:
            kind = "modified" if rel in owned else "unowned"
            report.drift.append((kind, rel))
            if not adopt:
                report.refused.append(rel)
        plan.writes[rel] = data

    for rel, recorded in sorted(owned.items()):
        if rel in files:
            continue
        path = root / rel
        if not path.is_file():
            report.drift.append(("stale-lock", rel))
            continue
        report.drift.append(("unexpected", rel))
        if _sha(path.read_bytes()) != recorded and not adopt:
            report.refused.append(rel)
        plan.removes.append(rel)

    pending: dict[str, str] = {}
    for (rel, region_id), body in render_regions(target, kit_dir).items():
        key = f"{rel}#{region_id}"
        want = _sha(body.encode("utf-8"))
        path = root / rel
        current = pending.get(rel)
        if current is None:
            if not path.is_file():
                report.drift.append(("region-missing", key))
                continue
            current = path.read_text(encoding="utf-8")
        try:
            have_body = read_region(current, region_id)
        except RegionMissingError:
            report.drift.append(("region-missing", key))
            continue
        regions[key] = want
        have = _sha(have_body.encode("utf-8"))
        if have == want:
            continue
        if owned_regions.get(key) == have or not have_body.strip():
            report.drift.append(("outdated", key))
        else:
            report.drift.append(("modified" if key in owned_regions else "unowned", key))
            if not adopt:
                report.refused.append(key)
        pending[rel] = replace_region(current, region_id, body)
    plan.region_writes = {rel: text.encode("utf-8") for rel, text in pending.items()}

    plan.new_lock = {
        "kit_version": KIT_VERSION,
        "compat_epoch": _compat_epoch(),
        "target": target.name,
        "files": dict(sorted(files.items())),
        "regions": dict(sorted(regions.items())),
    }
    return plan


def _atomic_write(path: Path, data: bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        tmp.chmod(mode)
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def _mode_for(data: bytes) -> int:
    return 0o755 if data.startswith(b"#!") else 0o644


def _new_backup_dir(root: Path) -> Path:
    base = root / STATE_DIR / "backup"
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    candidate = base / stamp
    n = 1
    while candidate.exists():
        candidate = base / f"{stamp}-{n}"
        n += 1
    candidate.mkdir(parents=True)
    return candidate


def _backup(root: Path, plan: _Plan) -> Path:
    backup = _new_backup_dir(root)
    manifest: dict[str, list[str] | bool] = {"created": [], "saved": []}
    for rel in sorted({*plan.writes, *plan.removes, *plan.region_writes}):
        src = root / rel
        if src.is_file():
            dst = backup / "files" / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            manifest["saved"].append(rel)  # type: ignore[union-attr]
        else:
            manifest["created"].append(rel)  # type: ignore[union-attr]
    lock_path = root / LOCK_NAME
    manifest["lock"] = lock_path.is_file()
    if lock_path.is_file():
        shutil.copy2(lock_path, backup / LOCK_NAME)
    (backup / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return backup


def revert_backup(root: Path) -> ApplyReport:
    """Restore the newest backup, then drop it so the next revert goes one further back."""
    report = ApplyReport(target="", root=root, mode="revert")
    base = root / STATE_DIR / "backup"
    backups = sorted(p for p in base.iterdir() if p.is_dir()) if base.is_dir() else []
    if not backups:
        report.status = EXIT_ERROR
        report.message = f"nothing to revert under {base}"
        return report
    backup = backups[-1]
    manifest = json.loads((backup / "manifest.json").read_text(encoding="utf-8"))
    for rel in manifest.get("created", []):
        path = root / rel
        if path.is_file():
            path.unlink()
            report.removed.append(rel)
    for rel in manifest.get("saved", []):
        data = (backup / "files" / rel).read_bytes()
        mode = (backup / "files" / rel).stat().st_mode & 0o777
        _atomic_write(root / rel, data, mode)
        report.written.append(rel)
    lock_path = root / LOCK_NAME
    if manifest.get("lock"):
        _atomic_write(lock_path, (backup / LOCK_NAME).read_bytes(), 0o644)
    elif lock_path.exists():
        lock_path.unlink()
    shutil.rmtree(backup)
    report.message = f"restored {backup.name}"
    return report


def apply(
    target: str | Target,
    root: str | Path | None = None,
    kit_dir: Path = KIT_DIR,
    check: bool = False,
    dry_run: bool = False,
    adopt: bool = False,
    revert: bool = False,
) -> ApplyReport:
    """Apply (or check, or revert) the kit's files for one target root."""
    spec = get_target(target) if isinstance(target, str) else target
    root_path = spec.resolve_root(root)
    if revert:
        result = revert_backup(root_path)
        result.target = spec.name
        return result
    mode = "check" if check else "dry-run" if dry_run else "apply"
    report = ApplyReport(target=spec.name, root=root_path, mode=mode)
    plan = _plan(spec, root_path, kit_dir, report, adopt)
    lock_changed = _lock_text(plan.new_lock) != (
        _lock_text(plan.lock) if plan.lock else b""
    )
    regions_missing = any(kind == "region-missing" for kind, _ in report.drift)

    if check:
        report.status = EXIT_ERROR if report.drift or lock_changed else EXIT_OK
        if lock_changed and not report.drift:
            report.message = f"{LOCK_NAME} does not match the kit"
        return report
    if report.refused:
        report.status = EXIT_ERROR
        return report
    if dry_run:
        report.status = EXIT_DEGRADED if regions_missing else EXIT_OK
        return report

    if plan.writes or plan.removes or plan.region_writes or lock_changed:
        report.backup = _backup(root_path, plan)
        for rel, data in sorted(plan.writes.items()):
            _atomic_write(root_path / rel, data, _mode_for(data))
            report.written.append(rel)
        for rel, data in sorted(plan.region_writes.items()):
            path = root_path / rel
            _atomic_write(path, data, path.stat().st_mode & 0o777)
            report.written.append(rel)
        for rel in plan.removes:
            (root_path / rel).unlink()
            report.removed.append(rel)
        _atomic_write(root_path / LOCK_NAME, _lock_text(plan.new_lock), 0o644)
    report.status = EXIT_DEGRADED if regions_missing else EXIT_OK
    return report

