"""Render the MCP tool and CLI references into docs/spec/TOOLS.md and CLI.md.

Both come from the live contract (``code_review_graph.contract``); tool purposes
are the first paragraph of each tool's docstring.

Usage: python scripts/gen_tool_reference.py [--check]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from code_review_graph import contract  # noqa: E402

HEADER = "<!-- GENERATED by scripts/gen_tool_reference.py from the contract — do not edit -->"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _purpose(description: str | None) -> str:
    first = (description or "").strip().split("\n\n", 1)[0]
    return " ".join(line.strip() for line in first.splitlines()) or "(no description)"


def render_tools_md(doc: dict[str, Any] | None = None) -> str:
    doc = doc or contract.build_contract()
    purposes = {t.name: _purpose(t.description) for t in contract._list_tools()}
    presets = doc["tool_presets"]
    lines = [
        HEADER,
        "",
        "# MCP tools",
        "",
        f"Contract {doc['contract_version']}, {len(doc['tools'])} tools. "
        "`serve --tools <preset|name,...>` (or `CRG_TOOLS`) limits what the server exposes.",
        "",
        "| Preset | Tools |",
        "|---|---|",
    ]
    for name, members in presets.items():
        shown = "every tool" if name == "all" else ", ".join(f"`{m}`" for m in members)
        lines.append(f"| `{name}` | {len(members)}: {shown} |")
    lines += [
        "",
        "Every response carries the `_graph` receipt (see [READINESS.md](READINESS.md)); "
        "errors use `{status: \"error\", error_code, message}`.",
        "",
        "| Tool | Read-only | Presets | Purpose |",
        "|---|---|---|---|",
    ]
    for tool in doc["tools"]:
        member_of = [p for p, members in presets.items() if tool["name"] in members]
        lines.append(
            f"| [`{tool['name']}`](#{tool['name']}) | {'yes' if tool['read_only'] else 'no'} "
            f"| {', '.join(member_of)} | {_cell(purposes.get(tool['name'], ''))} |"
        )
    for tool in doc["tools"]:
        lines += ["", f"## {tool['name']}", "", purposes.get(tool["name"], ""), ""]
        lines.append(
            f"Read-only: {'yes' if tool['read_only'] else 'no'}. "
            f"Presets: {', '.join(p for p, m in presets.items() if tool['name'] in m)}."
        )
        if not tool["params"]:
            lines += ["", "No parameters."]
            continue
        lines += ["", "| Parameter | Type | Required | Default |", "|---|---|---|---|"]
        for param in tool["params"]:
            default = (
                f"`{json.dumps(param['default'])}`" if "default" in param else ""
            )
            lines.append(
                f"| `{param['name']}` | `{_cell(param['type'])}` "
                f"| {'yes' if param['required'] else ''} | {_cell(default)} |"
            )
    return "\n".join(lines) + "\n"


def render_cli_md(doc: dict[str, Any] | None = None) -> str:
    doc = doc or contract.build_contract()
    lines = [
        HEADER,
        "",
        "# CLI commands",
        "",
        f"`code-review-graph <command>`; {len(doc['cli_commands'])} commands. "
        "Exit codes are listed in [READINESS.md](READINESS.md#exit-codes).",
        "",
        "| Command | Purpose | Options |",
        "|---|---|---|",
    ]
    for command in doc["cli_commands"]:
        options = ", ".join(f"`{o}`" for o in command.get("options", []))
        lines.append(
            f"| `{command['name']}` | {_cell(command.get('help') or '')} | {options} |"
        )
    return "\n".join(lines) + "\n"


TARGETS = {
    ROOT / "docs" / "spec" / "TOOLS.md": render_tools_md,
    ROOT / "docs" / "spec" / "CLI.md": render_cli_md,
}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    doc = contract.build_contract()
    stale = []
    for path, render in TARGETS.items():
        text = render(doc)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
    if stale:
        print("stale: " + ", ".join(stale) + "; run python scripts/gen_tool_reference.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
